[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
ring.workspace = true
serde.workspace = true
serde_derive.workspace = true

[dev-dependencies]
serde_json.workspace = true
